from fastapi import Request
from .settings import AuthSettings
from .protocols import AsyncUserProtocol, SyncUserProtocol, UserProtocol

class AsyncAuthenticator:
    def __init__(self, settings: AuthSettings, repo: AsyncUserProtocol) -> None: ...
    async def current_user(self, request: Request) -> UserProtocol: ...

class SyncAuthenticator:
    def __init__(self, settings: AuthSettings, repo: SyncUserProtocol) -> None: ...
    def current_user(self, request: Request) -> UserProtocol: ...
