from fastapi import Request
from .settings import AuthSettings

def extract_access_token(request: Request, settings: AuthSettings) -> str | None: ...
def extract_refresh_token(request: Request, settings: AuthSettings) -> str | None: ...
