from .settings import AuthSettings
from .protocols import AsyncUserRepo, SyncUserRepo, UserLike

class AuthServiceAsync:
    def __init__(self, settings: AuthSettings, repo: AsyncUserRepo) -> None: ...
    async def create_user(self, email: str, username: str, password: str) -> UserLike: ...
    async def create_superuser(self, email: str, username: str, password: str) -> UserLike: ...
    async def authenticate(self, username_or_email: str, password: str) -> UserLike: ...
    async def issue_token_pair(self, user: UserLike) -> tuple[str, str]: ...
    async def refresh_pair(self, refresh_token: str) -> tuple[str, str | None]: ...

class AuthServiceSync:
    def __init__(self, settings: AuthSettings, repo: SyncUserRepo) -> None: ...
    def create_user(self, email: str, username: str, password: str) -> UserLike: ...
    def create_superuser(self, email: str, username: str, password: str) -> UserLike: ...
    def authenticate(self, username_or_email: str, password: str) -> UserLike: ...
    def issue_token_pair(self, user: UserLike) -> tuple[str, str]: ...
    def refresh_pair(self, refresh_token: str) -> tuple[str, str | None]: ...
