from dataclasses import dataclass
from typing import  Literal


@dataclass(frozen=True)
class AuthSettings:
    secret_key: str
    algorithm: str = ...

    access_minutes: int = ...
    refresh_days: int = ...

    accept_header: bool = ...
    accept_cookie: bool = ...

    cookie_name_access: str = ...
    cookie_name_refresh: str = ...

    set_cookie_on_login: bool = ...
    cookie_secure: bool = ...
    cookie_samesite: Literal["lax", "strict", "none"] = "lax"
    cookie_max_age_access: int = ...
    cookie_max_age_refresh: int = ...

    refresh_rotation: bool = ...
    blacklist_after_rotation: bool = ...
