from .settings import AuthSettings

def create_access_token(settings: AuthSettings, *, subject: str) -> str: ...
def create_refresh_token(settings: AuthSettings, *, subject: str, jti: str) -> str: ...
def decode_access(settings: AuthSettings, token: str) -> dict: ...
def decode_refresh(settings: AuthSettings, token: str) -> dict: ...
