from typing import Any
from sqlalchemy.ext.asyncio import AsyncSession
from packages.authkit.src.authkit.protocols import UserProtocol


class SQLAlchemyAsyncUserRepo:
    def __init__(self, session: AsyncSession, user_model: type[Any]) -> None: ...
    async def get_by_id(self, user_id: int) -> UserProtocol | None: ...
    async def get_by_email_or_username(self, value: str) -> UserProtocol | None: ...
    async def create_user(
        self, *, email: str, username: str, password_hash: str,
        is_active: bool = ..., is_staff: bool = ..., is_superuser: bool = ...
    ) -> UserProtocol: ...
