from typing import Any
from sqlalchemy.orm import Session

from packages.authkit.src.authkit.protocols import UserProtocol

class SQLAlchemySyncUserRepo:
    def __init__(self, session: Session, user_model: type[Any]) -> None: ...
    def get_by_id(self, user_id: int) -> UserProtocol | None: ...
    def get_by_email_or_username(self, value: str) -> UserProtocol | None: ...
    def create_user(
        self, *, email: str, username: str, password_hash: str,
        is_active: bool = ..., is_staff: bool = ..., is_superuser: bool = ...
    ) -> UserProtocol: ...
